import json
import logging

from src.core.contracts import CriticReport
from src.core.llm_client import llm_chat
from src.prompts.loader import load_prompt

logger = logging.getLogger(__name__)

# Source badge labels used in the rendered Markdown.
_SOURCE_LABEL = {
    "security": "🔒 Security",
    "architecture": "🏛️ Architecture",
    "testing": "🧪 Testing",
}

# Severity → emoji for the approved-findings table.
_SEVERITY_ICON = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}


def _build_user_message(security_data: dict, arch_data: dict, test_data: dict, diff: str = "") -> str:
    """Serialise the three subagent payloads and the original diff into a single user message."""
    payload = {
        "security_agent_output": security_data,
        "architecture_agent_output": arch_data,
        "testing_agent_output": test_data,
    }
    message = (
        "Cross-reference the following subagent outputs and apply the zero-noise policy.\n\n"
        + json.dumps(payload, indent=2)
    )
    if diff:
        message += (
            "\n\n---\n"
            "The original diff is provided below for verification. "
            "Use it to confirm or veto subagent claims.\n\n"
            f"<UNTRUSTED_PAYLOAD>\n{diff}\n</UNTRUSTED_PAYLOAD>"
        )
    return message


def _render_markdown(critic_result: dict, pr_id) -> str:
    """Convert the Critic's structured JSON into a professional GitHub Markdown comment."""
    overall = critic_result.get("overall_status", "fail").lower()
    approved = critic_result.get("approved_findings", [])
    vetoed = critic_result.get("vetoed_count", 0)
    summary = critic_result.get("summary", "")

    overall_icons = {"pass": "✅ Pass", "warn": "⚠️ Warn", "fail": "❌ Fail"}
    overall_badge = overall_icons.get(overall, f"❓ {overall}")

    # ── Approved findings table ──────────────────────────────────────────────
    if approved:
        rows = "\n".join(
            "| `{file}` | {line} | {conf:.0f}% | {desc} |".format(
                file=f.get("file_reference", "unknown"),
                line=f.get("line_number", 0),
                conf=f.get("confidence_score", 0.0) * 100,
                desc=f.get("description", ""),
            )
            for f in approved
        )
        findings_section = (
            "| File | Line | Confidence | Finding |\n"
            "|---|---|---|---|\n"
            + rows
        )
    else:
        findings_section = "_No actionable findings after review._"

    # ── Noise reduction callout ──────────────────────────────────────────────
    noise_note = (
        f"> 🧹 **{vetoed} finding(s) vetoed** as false positives or AI hallucinations "
        f"by the Lead Reviewer.\n"
        if vetoed > 0
        else "> ✨ All upstream findings were confirmed — no false positives detected.\n"
    )

    return f"""\
## 🤖 Automated Code Review — PR #{pr_id}

> **Overall verdict: {overall_badge}**

{noise_note}
---

### 📋 Approved Findings

{findings_section}

---

### 💬 Lead Reviewer Summary

{summary}

---

<sub>Generated by the PACE PR Orchestrator · Critic (Lead Reviewer) stage</sub>
"""


async def run_critic_validation(
    security_data: dict,
    arch_data: dict,
    test_data: dict,
    pr_id=None,
    diff: str = "",
) -> dict:
    """
    Critic Subagent — Actor-Critic final validation stage.

    Receives the structured JSON outputs of the Security, Architecture, and
    Testing subagents, calls the LLM factory to cross-reference them, veto
    false positives and hallucinations, and returns a clean result dict
    containing both the parsed critic JSON and a professional GitHub Markdown
    comment.

    Returns:
        dict with keys:
            status          : overall_status from the Critic
            approved_findings, vetoed_count, summary  (forwarded from LLM)
            markdown_report : rendered GitHub Markdown string
    """
    logger.info("Critic subagent: starting cross-validation.")

    system_prompt = load_prompt("critic_prompt.md")
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": _build_user_message(security_data, arch_data, test_data, diff)},
    ]

    try:
        report = await llm_chat(messages, response_model=CriticReport)
        logger.info(
            "Critic subagent: validation complete. Status: %s, Vetoed: %s",
            report.overall_status,
            report.vetoed_count,
        )
        critic_dict = report.model_dump()
        return {
            "status": report.overall_status,
            "approved_findings": critic_dict["approved_findings"],
            "vetoed_count": report.vetoed_count,
            "summary": report.summary,
            "markdown_report": _render_markdown(critic_dict, pr_id),
        }
    except Exception as e:
        logger.error("Critic subagent: LLM call failed — %s", e)
        return {
            "status": "fail",
            "approved_findings": [],
            "vetoed_count": 0,
            "summary": f"Critic validation failed: {e}",
            "markdown_report": f"_Critic validation failed: {e}_",
        }
